import lightning from '../images/lightning.jpg'
import cigarette from '../images/cigarette.jpg'
import dangerScale from '../images/danger-scale.jpg'
import firefighter from '../images/firefighter.jpg'

// src/pages/Prevention.jsx
export default function Prevention() {
  return (
    <div>
      <div className="row">
        <section>
          <div className="content">
            <h2>Natural Causes</h2>
            <p>
              To prevent wildfires, it is first important to understand their causes. Here are some of the natural causes for wildfires:
            </p>
            <ul>
              <li>Lightning: the most common natural cause of wildfires, strikes can easily ignite vegetation. Dry lightning (with little to no rainfall) is especially dangerous.</li>
              <li>Volcanic eruptions: lava flows, hot ash, and pyroclastic flows can ignite surrounding forests and grasslands.</li>
              <li>Rockfalls or landslides: friction or sparks generated by falling rocks can ignite dry vegetation.</li>
              <li>Coal-seam: coal can oxidize when exposed to air, generating heat. Also with poor ventilation and heat build-up, the coal can reach ignition temperature and catch fire on its own.</li>
            </ul>
          </div>
        </section>
        <img src={lightning} alt="lightning"></img>
      </div>
      <div className="row">
        <section>
          <h2>Human Causes</h2>
          <div className="content">
            <ul>
              <li>Discarded cigarettes: burning cigarettes can be an ignition source.</li>
              <li>Unattended campfires: one of the leading causes of wildfires when the proper steps are not taken to extinguish them safely.</li>
              <li>Equipment malfunction: equipment that is improperly maintained or subjected to extreme weather can start fires. The main perpetrator of this is electrical distribution systems.</li>
              <li>Prescribed burning: sanctioned burns sometimes turn into wildfires if not carefully controlled, especially with the buildup of fire fuels.</li>
              <li>Burning debris: escaped embers from burn piles can be carried miles by the wind and ignite dry areas far away.</li>
            </ul>
          </div>
        </section>
        <img src={cigarette} alt="cigarette"></img>
      </div>
      <div className="row fire-danger-row">
        <img src={dangerScale} alt="fire danger scale"></img>
        <section>
          <h2>Fire Danger Scale</h2>
          <div className="content">
            <p>
              The fire danger scale is important to understand to prevent forest fires, especially for those planning on camping in or visiting high risk areas.
            </p>
            <ul>
              <li>Low (<strong><span style={{ color: 'green' }}>Green</span></strong>): Fires are unlikely to start without an intense heat sources. If any do they should be low intensity and easily extinguished.</li>
              <li>Moderate (<strong><span style={{ color: 'blue' }}>Blue</span></strong>): Some wildfires may ignite at a moderate size and intensity. Controlling wildfires should not be difficult and controlled burns can be performed with caution.</li>
              <li>High (<strong><span style={{ color: 'yellow' }}>Yellow</span></strong>): Wildfires are very possible due to weather factors and will be hard to control in areas with heavy, continuous fuel if there are high winds.</li>
              <li>Very High (<strong><span style={{ color: 'orange' }}>Orange</span></strong>): Fires will start easily, and suppression efforts may not be able to keep up with the spread. Outdoor burns are not recommended.</li>
              <li>Extreme (<strong><span style={{ color: 'red' }}>Red</span></strong>): Wildfires can start and spread very quickly with the potential to become huge and uncontrollable. Fire behavior is likely to be extreme and erratic, and no outdoor burning should be allowed.</li>
            </ul>
          </div>
        </section>
      </div>
      <div className="row">
        <section>
          <h2>Practice Fire Safety</h2>
          <div className="content">
            <ul>
              <li>Only build campfires in designated areas</li>
              <li>Don’t smoke in forested areas</li>
              <li>Be aware of fire bans and the fire danger scale</li>
              <li>Never leave litter that could concentrate sunlight and start fires</li>
              <li>Never dump hot coals or ashes in the forest</li>
            </ul>
          </div>
        </section>
        <section>
          <h2>Join Wildland Firefighting</h2>
          <div className="content">
            <p>
              Below are some job boards and informative sites on employment for wildland firefighting:
            </p>
            <ul>
              <li><a href="https://www.fs.usda.gov/managing-land/fire/careers">USDA Forest Service</a></li>
              <li><a href="https://www.conservationjobboard.com/wildland-firefighter-jobs">Conservation Job Board</a></li>
              <li><a href="https://fireecology.org/jobs-board?srsltid=AfmBOopAj8Oiol8nMFwqsbkngCmHMu0cSdRbxcFyaFOefdhiAGgevyrq">Association for Fire Ecology</a></li>
            </ul>
          </div>
        </section>
        <img src={firefighter} alt="wildland fire fighter"></img>
      </div>
    </div >
  );
}